### PR TITLE
add individual trim speed settings

### LINKED ISSUE #534: Individual trim speed percentage setting sliders for pitch, roll, and rudder
**Is your feature request related to a problem? Please describe.**
I'd like to turn down aileron trim to 25%, but keep elevator trim at 50%, currently this is not possible with a single setting that effects all trim controls.

**Describe the solution you'd like**
Add a separate Trim Speed setting for each trim control

### PR DESCRIPTION
**Pull request by Drofseh**
close #534

### CODE REVIEW

**Comment by Drofseh** [comment]
I've flown with this in a couple missions now and it's working well, but it might be better to just make the a setting a slider from 1 to 100 and then divide the setting input by 100 to get 0.01 to 1.

That would be more customizable for the end user and also reduce all the elseif code to just a single division per trim setting axis.

Thoughts?

**Comment by callmepartario** [comment]
Sure - I'm not sure how to make a slider in the UI, though. Is that available?

**Comment by callmepartario** [comment]
i'll take a look through some other modules and see what i can dig up from their special configs.

**Comment by callmepartario** [comment]
okay, yeah, this looks possible. lemme play around with it - if i can get that going, i'll merge you in and take it from there.

**Comment by callmepartario** [comment]
I've gone ahead and added these changes in my own commit at https://github.com/heclak/community-a4e-c/commit/d29acd0a17decd9b56f2b4534e42b1138403e8c3 -- thanks for the guide, it made it a snap. I made three sliders and respaced the special menu out.

You can safely fold these changes into your existing install if you like! I also added you to the contibutors list in the readme.

**Comment by Drofseh** [comment]
Sounds good to me!
I am drofseh in the A-4E discord if you want to give me the contributor tag there as well ;)

**Comment by Drofseh** [comment]
It looks like you missed this though, so the sliders won't actually apply the trim rates.

https://github.com/heclak/community-a4e-c/pull/535/files#diff-58808eae6ef1284c19b977e23fae3b4a505f17539dd799b3dc894b24ece50113R301-R329

**Comment by Drofseh** [comment]
Oh, maybe I'm reading https://github.com/heclak/community-a4e-c/commit/d29acd0a17decd9b56f2b4534e42b1138403e8c3 wrong

**Pull request closed without merging**
