### PR TITLE
Change control indicator to use logarithmic scaling for NW caster angle

### PR DESCRIPTION
**Pull request by Drofseh**
Changes the scaling of the nose wheel caster angle to use a logarithmic scale instead of linear scale.
This makes it much easier to see the angle of the wheel at the lower angles that are more typically seen during taxiing.

Scale looks like this:
c052ca61c30118f2e085e7ef529e77d0

### CODE REVIEW

**Comment by 08jne01** [comment]
Nice work I assume you have tested it and it works?

**Comment by Drofseh** [comment]
> Nice work I assume you have tested it and it works?

Yes, it is working, although I've just discovered that since 0.5 and -0.5 are the limits of the input, the highest the indicator can go is to the line I've marked 50%, so I'm going to test scaling the input up to 1 and -1 to reach 100% on each side of the indicator

**Comment by Drofseh** [comment]
So it turns out that 1 and -1 will take the NW angle indicator way off the screen lol.
0.67 and -0.67 are the values to put it right in the corner, so the scale of the output has been adjusted to do that.

This PR is now complete

**Comment by 08jne01** [comment]
Nice work.

**Pull request merged**
